// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using marvel_api.Models;

namespace marvel_api.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("marvel_api.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            FirstName = "Anthony",
                            LastName = "Stark",
                            Status = "Deceased"
                        },
                        new
                        {
                            CharacterId = 2,
                            FirstName = "Steven",
                            LastName = "Rogers",
                            Status = "Alive"
                        },
                        new
                        {
                            CharacterId = 3,
                            FirstName = "Peter",
                            LastName = "Quill",
                            Status = "Alive"
                        },
                        new
                        {
                            CharacterId = 4,
                            FirstName = "Thor",
                            LastName = "Odinson",
                            Status = "Alive"
                        },
                        new
                        {
                            CharacterId = 5,
                            FirstName = "Natalia",
                            LastName = "Romanoff",
                            Status = "Deceased"
                        },
                        new
                        {
                            CharacterId = 6,
                            FirstName = "T'Challa",
                            Status = "Alive"
                        },
                        new
                        {
                            CharacterId = 7,
                            FirstName = "Bruce",
                            LastName = "Banner",
                            Status = "Alive"
                        },
                        new
                        {
                            CharacterId = 8,
                            FirstName = "Scott",
                            LastName = "Lang",
                            Status = "Alive"
                        },
                        new
                        {
                            CharacterId = 9,
                            FirstName = "Phillip",
                            LastName = "Coulson",
                            Status = "Deceased"
                        },
                        new
                        {
                            CharacterId = 10,
                            FirstName = "Nick",
                            LastName = "Fury",
                            Status = "Alive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
